spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource 
    url: jdbc:mysql://localhost:3306/world?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
server:
  port: 9001
    